services:
  - type: web
    name: student-backend
    env: python
    rootDir: backend
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn student_project.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: django-insecure-change-this-to-a-random-string
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
